### ISSUE TITLE
Extentions

### ISSUE THREAD

**Issue by JoshuaRL** [YunoHost-Apps/snserver_ynh#13]
I'd like to run self-hosted extensions to test out before deciding to buy.  The main page documentation mentions extentions and https://mydomain.tld/yunohost/admin/#/apps/snserver/config-panel has an option to point extensions to what I think is the web app, but I haven't seen any difference.  Are there any included extensions with this or a way to load them?

**Comment by FabianWilkens** [comment]
Hi,

yes all official open-source Standard Notes Extensions I could find are included in this package.
If you install this server, the extensions will be hosted as well.

After the registration via the web, desktop or mobile app the user will get an email with install instructions.

If you decide to pay for the extensions on the official Standard Notes website, than you will get more extenisons and they are always up-to-date.

**Comment by brimwats** [comment]
If your server doesn't have email like mine @JoshuaRL use this https://github.com/kylejbrk/standard-notes-open-extended

**Comment by JoshuaRL** [comment]
Thanks @brimwats that's exactly what I needed.  But I had issues with that repo, https://github.com/JokerQyou/snextensions seemed to work instead, which is listed as what it's based on.
