### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/snserver_ynh#15]
Hello!

Here are the logs:

https://paste.yunohost.org/raw/ehezuzicab

**Comment by FabianWilkens** [comment]
Hi,

fixed this issue yesterday. And today say changed it again.
#14

Will fix it when I am home.

Thank you

**Comment by FabianWilkens** [comment]
Should be fixed again.

Hopefully they won't yank the package again.

And yunohost app list was now updated as well.

**Comment by brimwats** [comment]
Its resolved! thanks so much!
