### ISSUE TITLE
Typo in upgrade script

### ISSUE THREAD

**Issue by SecretestSquirrel** [YunoHost-Apps/snserver_ynh#17]
Tiny error, but might as well fix when you have time. Should be "Syncing" not "Synicing".
Appreciate the work.

https://github.com/YunoHost-Apps/snserver_ynh/blob/e8db15c97db16f68d6453970a9dff74d5136017b/scripts/upgrade#L263

**Comment by FabianWilkens** [comment]
Thank you.
Will fix this at the next version.
