### ISSUE TITLE
Some login issues with the apps

### ISSUE THREAD

**Issue by TROMsite** [YunoHost-Apps/snserver_ynh#27]
Can you please have a look at the discussion here https://github.com/standardnotes/standalone/issues/5 and my comment https://github.com/standardnotes/standalone/issues/5#issuecomment-870977267 - because it may be an issue with this ynh package.

**Comment by FabianWilkens** [comment]
I can take a look at the weekend.

Maybe there were updates to the official web app and smartphone app. Which is not compatible to the server version anymore.
Idk.

**Comment by TROMsite** [comment]
They said so. This might be the case. Perhaps the ynh package needs an upgrade to the latest standard notes server and webapp.

**Comment by FabianWilkens** [comment]
Year. Just read there comment. So I will see if it helps to upgrade both.

**Comment by FabianWilkens** [comment]
@TROMsite 
If you like you can try and install the updated version. #28 
`sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.07.06`

Now the server is up-to-date.
Also the extensions are updated as far as possible.

**Comment by TROMsite** [comment]
Awesome! I'll for sure do so and let you know if that fixes the issues!

**Comment by TROMsite** [comment]
So to be clear: I have it already installed, both the server and the webapp. Should I remove the server and install as you suggested above? Or should I simply try to upgrade the server, and if so how to do it properly?

**Comment by FabianWilkens** [comment]
Thanks for testing it.


You can install it a second time with:
`sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.07.06`
Or upgrade your installation with:
`sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.07.06`

**Comment by TROMsite** [comment]
It works now! Fantastic! Tested the desktop app + android app. I can login no problem. And the Plus Editor also works! Really great! Thanks for updating it and you can close the issue if you think is all done and we need no more testing.

**Comment by FabianWilkens** [comment]
Thanks nice to hear.
I will close the issue with the merge of the PR.
But there are still a few things to do.
