### ISSUE TITLE
snserver cannot start

### ISSUE THREAD

**Issue by TROMsite** [YunoHost-Apps/snserver_ynh#31]
I see this error after I upgraded it as you said:
![image](https://user-images.githubusercontent.com/38043315/125169585-2fa60a00-e1ab-11eb-9f86-9d566539328d.png)

Thing is the server works fine since I can connect to it from any device and web....maybe the service is called differently now?

![image](https://user-images.githubusercontent.com/38043315/125169619-52382300-e1ab-11eb-99b6-4b659b413c7a.png)

**Comment by FabianWilkens** [comment]
Before the service was just snserver and now there are the other 5 services.
I will remove the old service during the upgrade.

Thanks
