### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by SecretestSquirrel** [YunoHost-Apps/snserver_ynh#34]
### Describe the bug

*Unable to sync application with Standard Notes server.*

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.2.6
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 3.22.8~ynh2

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. Simply open application in mobile or web, see unable to sync. Attempted to restart snserver, nothing I tried had any effect. 
### Expected behavior

*Sync application with Standard Notes Server running. Hoping that someone is able to point me in the right direction after viewing the logs in pastebin, link included below.*

### Logs

https://paste.yunohost.org/inonunebam

**Comment by FabianWilkens** [comment]
Hi,

sorry for you troubles.

It is already fix, but it is not offering to update yet.

You can make the upgrade manually:
`sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh`

**Comment by User-Deleted** [comment]
## Context

    Hardware: RPI 4b at home
    YunoHost version: 4.3.6.2
    I have access to my server: Through SSH & through the webadmin

<hr>

I am having this same issue. I have updated the app succesfully.
```
admin@YNH:~ $ sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh
Info: Now upgrading snserver...
Success! snserver is already up-to-date
Success! Upgrade complete
```

It was mentioned here that I may need to adjust the payload size for nginx.
https://github.com/standardnotes/syncing-server-js/issues/72

Does anyone know how to do that for this architecture?

I also wonder if there could be an issue with swap since I am using a micro sd card...

**Comment by FabianWilkens** [comment]
Hi.

it was another problem here before.

You can try and fix your problem.

Open this file.
/etc/nginx/domain.tld.conf/snserver.conf
domain.tld is your domain
(Could be a different path, but than I have to take a look)

And put this after Line 8

```
# set client body size to 2M
client_max_body_size 2M;

```

You can also try and increase the 2M, if it is not enough.

After that you need to reload nginx.
`sudo systemctl reload nginx`

**Comment by User-Deleted** [comment]
> Hi.
> 
> it was another problem here before.
> 
> You can try and fix your problem.
> 
> Open this file. /etc/nginx/domain.tld.conf/snserver.conf domain.tld is your domain (Could be a different path, but than I have to take a look)
> 
> And put this after Line 8
> 
> ```
> # set client body size to 2M
> client_max_body_size 2M;
> ```
> 
> You can also try and increase the 2M, if it is not enough.
> 
> After that you need to reload nginx. `sudo systemctl reload nginx`

Worked.

Thanks for your help. Sorry. Didn't realize this was a separate issue.

**Comment by FabianWilkens** [comment]
That's great.

I will merge this line, so this will work for everybody.
Thanks
