### ISSUE TITLE
Manual CLI Upgrade Failed

### ISSUE THREAD

**Issue by JoshuaRL** [YunoHost-Apps/snserver_ynh#36]
### Describe the bug

I've been having trouble with the server being able to sync and connect to desktop and mobile clients. I found [Standard Notes Issue #21](https://github.com/standardnotes/standalone/issues/21) and it seems like it's because I was on an old legacy Ruby version instead of the new Node version. I found #34 and ran the CLI upgrade since nothing showed on the Webadmin panel as available. It failed and reported as breaking APT.

### Context

- Hardware: Online VPS
- YunoHost version: 4.2.6.1 Stable
- I have access to my server: *Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: followed directions from #34 
- If upgrading, current package version: 3.22.8~ynh2

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh
    ```

### Expected behavior

It seems like this upgrade was from the legacy Ruby server to the new Node server. It seems to fail during the swap with either the Node startup or a memory leak with the script 

### Logs

https://paste.yunohost.org/raw/okuhamafod

Scrubbed CLI:
https://paste.yunohost.org/tiqipedena.rb

**Comment by FabianWilkens** [comment]
It seems that your server has not enough memory for the install process.

Unfortunately the new server needs more resources.


You can try and at some swap memory.
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-debian-10


Otherwise I will have to change the upgrade and install scripts and add some swap memory there.

**Comment by FabianWilkens** [comment]
@JoshuaRL 
Have you tried to add swap memory manually to your server?
Could you install the upgrade afterwards?

**Comment by JoshuaRL** [comment]
@FabianWilkens 
I have not, I'm really sorry but life got crazy busy immediately after I put this ticket in. I'll reply back when I get a chance to.

Thanks!

**Comment by imacfan** [comment]
> @JoshuaRL
> Have you tried to add swap memory manually to your server?
> Could you install the upgrade afterwards?

I have added it, did not work for me.. I tried upgrade through web admin portal after adding swap memory. Created a separate issue for the same.

**Comment by FabianWilkens** [comment]
This issue should be fixed.
Please reopen this issue If you still have problems.
