### ISSUE TITLE
Upgrade? Standalone : Syncing Server JS

### ISSUE THREAD

**Issue by imacfan** [YunoHost-Apps/snserver_ynh#40]
It seems latest version of desktop and Android apps do not work with this version of snserver

Standalone is the latest version of sync server which works with all apps. I had to downgrade my desktop app for now to make it sync with snserver.

I guess this will be upgraded soon?

**Comment by FabianWilkens** [comment]
Which version of snserver and desktop, mobile app was working for you?
And which combination is not working.

I will try to reproduce this.

**Comment by imacfan** [comment]
> Which version of snserver and desktop, mobile app was working for you?
> 
> And which combination is not working.
> 
> 
> 
> I will try to reproduce this.

Not working combination - Latest version on Yunohost V 2021.07.24~ynh2 and latest version of desktop app V 3.8.18..
If if take older version I.e v3.6 of desktop app it works fine.

Latest version of ios app 3.6.22 works fine. But latest android app doesn't

**Comment by FabianWilkens** [comment]
Thats wierd.

I am using the exact same versions.
It is working on my side.

Do you remember what the problem was.
Unable to sync data
Unable to login
Unable to connect

Most of the time I see there a message like that.

**Comment by imacfan** [comment]
Ok. I upgraded from V 3.6 to 3.8.18. Now it works fine. 

When i directly installed V 3.8.18. It was giving issues while login. 

Maybe you upgraded your desktop app. Try deleting the data folder and app. Then run the latest version directly

**Comment by FabianWilkens** [comment]
Still no problems after deleting all.
Yes I have enabled auto update.

Maybe there was a fault during the installation.

But now you have also the android app which was not working, right?

**Comment by imacfan** [comment]
Strange .. that's also working now. Probably, some installation issue. I did a reinstall of server..> installation
