### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by imacfan** [YunoHost-Apps/snserver_ynh#45]
### Describe the bug

I am try to upgrade from "2021.07.24~ynh3" to latest version but it fails.
### Context

- Hardware: * Raspberry Pi at home...*
- YunoHost version: 4.2.8.2 (stable).
- I have access to my server: *through the webadmin *
- Using, or trying to install package version/branch: 4.2.8.2 (stable).
- If upgrading, current package version: **

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. *Go to 'System update*
   2. *Click on upgrade application*

### Expected behavior

upgrade to latest version of snserver

### Logs

*When an operation fails, YunoHost provides a simple way to share the logs.*

https://paste.yunohost.org/raw/feguvisuge

**Comment by FabianWilkens** [comment]
@imacfan 
Can you please observe your ram usage during the installation with top, htop or similar.
In the other issue you mention that you created swap manually. How much was it?
The latest upgrade will also create 1.5gb swap.

@echapon
You reacted with a thums up.
Do you have the same problem?
CAn you also share your install/upgrade logs?

**Comment by echapon** [comment]
@FabianWilkens yes I did meet the same problem. See the log for the upgrade: https://paste.yunohost.org/raw/olohizaxub
I see now though that the fatal error "Allocation failed - JavaScript heap out of memory" is not exactly the same for imacfan.
NB: I monitored the RAM and swap usage (with Netdata) and did not see anything suspicious. I have 8GB of RAM and 2GB of swap, and both were far from being full at the time of the crash.
![image](https://user-images.githubusercontent.com/5276688/132926682-3fe455fd-9f88-4cff-a44f-63a04dc55b1e.png)
I also tried with ```SD_CARD_CAN_SWAP=1``` but same result (https://paste.yunohost.org/raw/eyowagaqet).

**Comment by imacfan** [comment]
You, same .. no RAM issues. I created 512 MB swap file also.

**Comment by TheGreatBeginner777** [comment]
Hi all,

I'm experiencing the same problem but I'm installing it for the first time. RPI 4B 8GB version with swap of 4GB. I tried also checking ram usage but it was newer above 310MB while swap was on 0MB.  I manage to install this version on my test device (HP 450 laptop) without any problems.
Log: [https://paste.yunohost.org/raw/zavageqede](url)

**Comment by FabianWilkens** [comment]
Thanks for your reports.

Unfortunately I could not recreate this problem.

I created two new versions.
Hopefully one of them can fix your issues.
**Both versions are not tested yet.** 

Here the snserver is updated to the latest version from 09.09.2021.
sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.09.09
sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.09.09

Here I have increased the swap file size and the amount Node can use during the install.
I increased the swap file from 1.5GB to 2.0 GB
And Node can now use 6GB instaed of 4GB.
In all test I did before, the installations never used more than 1.5GB at a time.
sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/help_#45
sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh/tree/help_#45

**Comment by imacfan** [comment]
I tried both approaches. Still getting same issue. Log below:

https://paste.yunohost.org/raw/ofusulehih

**Comment by TheGreatBeginner777** [comment]
Hi.

@FabianWilkens 
1. I tried with:
> sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/2021.09.09

but I get the same _JavaScript heap out of memory_
Logs for this one are available here: [https://paste.yunohost.org/raw/ikiluwijod](url)

2. For the:

> sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/help_%2345

I get this error: 

> Error: Could not fetch sources files, is the URL correct?

**Comment by FabianWilkens** [comment]
> > sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/help_%2345
> 
> I get this error:
> 
> > Error: Could not fetch sources files, is the URL correct?


Sorry
Try it like this:
sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/help_#45

**Comment by TheGreatBeginner777** [comment]
With this:

> sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/help_#45

it managed to install it self :) with the message 

> Success! Installation completed

Thanks!

One more since we are on this subject. What are the implication(s) to application installed in this way? Should I be worried about something? Will I be able to later on update this app through _System update_ which is part of YNH admin panel?

**Comment by FabianWilkens** [comment]
> > Success! Installation completed

That's Great
 
> One more since we are on this subject. What are the implication(s) to application installed in this way? Should I be worried about something? Will I be able to later on update this app through _System update_ which is part of YNH admin panel?

Year thats not a problem.
When there is an update you will see it under "System update"

**Comment by FabianWilkens** [comment]
@imacfan 
Did you had the same issue on the secound solution (https://github.com/YunoHost-Apps/snserver_ynh/issues/45#issuecomment-917605555)
After correction the link, it was working.

**Comment by imacfan** [comment]
> @imacfan 
> 
> Did you had the same issue on the second solution (https://github.com/YunoHost-Apps/snserver_ynh/issues/45#issuecomment-917605555)
> 
> After correction the link, it was working. 

Yes , it worked with this link
