### ISSUE TITLE
login issues, creating account and or two factor problem, not sure... help please

### ISSUE THREAD

**Issue by ihaveimpulses** [YunoHost-Apps/snserver_ynh#75]
### Describe the bug

I installed Standard Notes Server no problem, beyond that I tried looking over documentation, I even read on the gitpage here that it doesn't support the ldap accounts, so after poking around for what seemed like hours to me I tried to sign in. I noticed the default points to api.standardnotes, so I tried api.mydomain and nothing, so I tried just the "mydomain.com" for the server with my ldap account and I got a popup for two factor.. I never setup two factor, plus I'm not getting an email for it so I don't know what I'm  doing wrong or how to make this work :(

### Context

- Hardware: *Old computer
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH | through the webadmin | 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes*
  - If yes, please explain: disabled ipv6
- Using, or trying to install package version/branch: I tried testing and regular for sns server

### Steps to reproduce

launch standardnotes, set my server to be "mydomain.com" and try to login with my sso, pops up

### Expected behavior

Logins in?

### Logs

LOGFILE: journalctl
-- Logs begin at Sun 2022-07-03 15:34:50 ADT, end at Tue 2022-07-05 08:08:37 ADT. --
Jul 03 15:36:31 systemd[1]: Started StandardNotes auth.
Jul 03 15:51:15 systemd[1]: Stopping StandardNotes auth...
Jul 03 15:51:15 systemd[1]: snserver-auth.service: Main process exited, code=exited, status=1/FAILURE
Jul 03 15:51:15 systemd[1]: snserver-auth.service: Failed with result 'exit-code'.
Jul 03 15:51:15 systemd[1]: Stopped StandardNotes auth.
Jul 03 16:11:17 systemd[1]: Started StandardNotes auth.
Jul 03 16:13:10 systemd[1]: Stopping StandardNotes auth...
Jul 03 16:13:10 systemd[1]: snserver-auth.service: Main process exited, code=exited, status=1/FAILURE
Jul 03 16:13:10 systemd[1]: snserver-auth.service: Failed with result 'exit-code'.
Jul 03 16:13:10 systemd[1]: Stopped StandardNotes auth.
Jul 03 16:25:16 systemd[1]: Started StandardNotes auth.
Jul 03 16:36:15 systemd[1]: Stopping StandardNotes auth...
Jul 03 16:36:15 systemd[1]: snserver-auth.service: Main process exited, code=exited, status=1/FAILURE
Jul 03 16:36:15 systemd[1]: snserver-auth.service: Failed with result 'exit-code'.
Jul 03 16:36:15 systemd[1]: Stopped StandardNotes auth.
Jul 03 16:48:53 systemd[1]: Started StandardNotes auth.

LOGFILE: /var/log/snserver/auth.log
yarn run v1.22.19
$ node dist/bin/server.js
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"caruso.group","pid":28103,"time":"2022-07-03T19:48:53.974Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
{"message":"Server started on port 3002","level":"info"}

**Comment by FabianWilkens** [comment]
Hi,

I will take a look when I am home.

In the Standard notes app you need to enter the same url as the snserver.
Then in the app you can create a new account.
SSO is not supported.

Did you re-started the auth server by hand?
Or did it restart itself all the time?

**Comment by ihaveimpulses** [comment]
this can be closed, it started working
