### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by FabianWilkens** [YunoHost-Apps/snserver_ynh#81]
It is currently not possible to install the Standard Notes server due to some npm issues.
Unfortunatly i don't have time to work on this for the next two weeks.
So it may take same time to solve this.

https://github.com/YunoHost/issues/issues/2056

**Comment by tituspijean** [comment]
Let's keep issues for apps in the YunoHost-Apps organization. 😉 Quote from @aarontrom in the initial issue:

> I did the upgrade to yunohost 11 and it went soo smooth. Thanks for the amazing work you're doing! 1 app that failed for me was the upgrade and install of Standard Notes. I tried to upgrade it before the migration to YNH 11, then it didn't work, so I did the migration, removed standard notes and tried to reinstall it which also failed. I have the 2 logs here: [paste.yunohost.org/raw/ojalorukub](https://paste.yunohost.org/raw/ojalorukub) and [paste.yunohost.org/raw/uregeqohoz](https://paste.yunohost.org/raw/uregeqohoz)

**Comment by FabianWilkens** [comment]
@aarontrom 
Can you try to upgrade or install the StandardNotes Server?

**Comment by TheGreatBeginner777** [comment]
hi @FabianWilkens 
I'm having the same issue as shown in 1st post. For me the update failed with this log
[https://paste.yunohost.org/raw/ocubamosut](url)
Can you have a look at it and give some clues?

**Comment by FabianWilkens** [comment]
@TheGreatBeginner777 
You actually have a new problem. Can you check how much RAM you have available before starting the upgrade?
Swap is created during installation, but it could be that this is still not enough.

You could try and create additional swap for the installation.

**Comment by TheGreatBeginner777** [comment]
@FabianWilkens 
Should this be enough for the upgrade?

> total        used        free      shared  buff/cache   available
> Mem:          7.7Gi       1.1Gi       3.9Gi       8.0Mi       2.7Gi       6.4Gi
> Swap:         4.1Gi        35Mi       4.1Gi

**Comment by FabianWilkens** [comment]
Yes this should be enough.

Can you try this:
```
sudo yunohost app install https://github.com/YunoHost-Apps/snserver_ynh/tree/patch-1
or
sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh/tree/patch-1
```

**Comment by TheGreatBeginner777** [comment]
success!
this one was my victory
``sudo yunohost app upgrade snserver -u https://github.com/YunoHost-Apps/snserver_ynh/tree/patch-1``

thanks a lot for your swift workaround!

**Comment by aarontrom** [comment]
> @aarontrom Can you try to upgrade or install the StandardNotes Server?

@FabianWilkens I saved all my data via a backup, removed StandardNotes Server, did a fresh installation and now it works again! 
Thank you so much! Highly appreciated - I think Standard Notes is the best notes application to have notes syncing between phone and laptop via snserver.
